### ISSUE TITLE
Owner do not change after accepting an offer 

### ISSUE THREAD

**Issue by MatthiasHerzog2000** [ChristophThiel/bfk-portal-server#10]
After an offer was accepted the owner didn't change at all but the two Dienste suddenly got Participations who where the owner from the other so after an offer was accepted the dienste involved would look something like this:

Dienst1 owner: christoph ZImprich, participant : christoph Thiel
Dienst2 owner : christoph Thiel participant : christoph Zimprich

**Comment by ChristophThiel** [comment]
I have forgotten to update the changed appointment.

**Comment by ChristophThiel** [comment]
I have forgotten to update the changed appointment.

**Comment by ChristophThiel** [comment]
I have forgotten to update the changed appointment.

**Comment by ChristophThiel** [comment]
I have forgotten to update the changed appointment.

**Comment by ChristophThiel** [comment]
I have forgotten to update the changed appointments.
