### ISSUE TITLE
CORS Policy not suitable for sending Files

### ISSUE THREAD

**Issue by MatthiasHerzog2000** [ChristophThiel/bfk-portal-server#5]
When trying to send a file to the server via the route _api/file/upload_ CORS blocks the request with following error:
![image](https://user-images.githubusercontent.com/22956042/47188596-fe20ec80-d338-11e8-9018-60d73b5df266.png)

**Comment by ChristophThiel** [comment]
Since the client is hosted by the kestrel server, cors would not be necessary anymore.
