### ISSUE TITLE
When Updating Appointment the participants get doubled

### ISSUE THREAD

**Issue by MatthiasHerzog2000** [ChristophThiel/bfk-portal-server#6]
When I try to update an appointment the participants get doubled e.g. I start with 12 participants after the update they are 24.
Proof: 
Request:
![image](https://user-images.githubusercontent.com/22956042/47190210-82c33900-d340-11e8-821d-b2ac2842f8d1.png)
and after fetching appointments again: 
![image](https://user-images.githubusercontent.com/22956042/47190287-ce75e280-d340-11e8-8489-9a3d6c6fe5fc.png)

**Comment by ChristophThiel** [comment]
I had to delete the participations. It is fixed.
