### ISSUE TITLE
Deleting as Owner or Admin doesn't work

### ISSUE THREAD

**Issue by MatthiasHerzog2000** [ChristophThiel/bfk-portal-server#7]
I tried to delete an appointment with Christoph Zimprich who is Admin and also was the owner of the file but I got Statuscode 400 Bad Request:
![image](https://user-images.githubusercontent.com/22956042/47190361-35939700-d341-11e8-89fd-f72090d03e4a.png)

**Comment by ChristophThiel** [comment]
Problem solved. The annotation [FromHeader] in the action is not for this purpose.
