### ISSUE TITLE
When trying to set a Dienst to MarktplatzDienst the Dienst get a Participant

### ISSUE THREAD

**Issue by MatthiasHerzog2000** [ChristophThiel/bfk-portal-server#9]
When trying to send a Dienst to the Marketplace with the route _api/appointment/offer/{id}_ the Dienst gets a Participant
before offering the Dienst:
![image](https://user-images.githubusercontent.com/22956042/47257101-aa71e880-d489-11e8-85c7-515e2b1899a2.png)

after offering the Dienst:
![image](https://user-images.githubusercontent.com/22956042/47257112-ffadfa00-d489-11e8-9f65-9305196a6a0b.png)

**Comment by ChristophThiel** [comment]
I have checked this issue with Postman. In my case no participants were added.
